ADDR_MODEL_NUMBER = 0
LEN_MODEL_NUMBER = 2

ADDR_FIRMWARE_VERSION = 2
LEN_FIRMWARE_VERSION = 1

ADDR_ID = 3
LEN_ID = 1

ADDR_BAUD_RATE = 4
LEN_BAUD_RATE = 1

ADDR_RETURN_DELAY_TIME = 5
LEN_RETURN_DELAY_TIME = 1

ADDR_CW_ANGLE_LIMIT = 6
LEN_CW_ANGLE_LIMIT = 2

ADDR_CCW_ANGLE_LIMIT = 8
LEN_CCW_ANGLE_LIMIT = 2

ADDR_TEMPERATURE_LIMIT = 11
LEN_TEMPERATURE_LIMIT = 1

ADDR_MIN_VOLTAGE_LIMIT = 12
LEN_MIN_VOLTAGE_LIMIT = 1

ADDR_MAX_VOLTAGE_LIMIT = 13
LEN_MAX_VOLTAGE_LIMIT = 1

ADDR_MAX_TORQUE = 14
LEN_MAX_TORQUE = 2

ADDR_STATUS_RETURN_LEVEL = 16
LEN_STATUS_RETURN_LEVEL = 1

ADDR_ALARM_LED = 17
LEN_ALARM_LED = 1

ADDR_SHUTDOWN = 18
LEN_SHUTDOWN = 1

ADDR_TORQUE_ENABLE = 24
LEN_TORQUE_ENABLE = 1

ADDR_LED = 25
LEN_LED = 1

ADDR_CW_COMPLIANCE_MARGIN = 26
LEN_CW_COMPLIANCE_MARGIN = 1

ADDR_CCW_COMPLIANCE_MARGIN = 27
LEN_CCW_COMPLIANCE_MARGIN = 1

ADDR_CW_COMPLIANCE_SLOPE = 28
LEN_CW_COMPLIANCE_SLOPE = 1

ADDR_CCW_COMPLIANCE_SLOPE = 29
LEN_CCW_COMPLIANCE_SLOPE = 1

ADDR_GOAL_POSITION = 30
LEN_GOAL_POSITION = 2

ADDR_MOVING_SPEED = 32
LEN_MOVING_SPEED = 2

ADDR_TORQUE_LIMIT = 34
LEN_TORQUE_LIMIT = 2

ADDR_PRESENT_POSITION = 36
LEN_PRESENT_POSITION = 2

ADDR_PRESENT_SPEED = 38
LEN_PRESENT_SPEED = 2

ADDR_PRESENT_LOAD = 40
LEN_PRESENT_LOAD = 2

ADDR_PRESENT_VOLTAGE = 42
LEN_PRESENT_VOLTAGE = 1

ADDR_PRESENT_TEMPERATURE = 43
LEN_PRESENT_TEMPERATURE = 1

ADDR_REGISTERED = 44
LEN_REGISTERED = 1

ADDR_MOVING = 46
LEN_MOVING = 1

ADDR_LOCK = 47
LEN_LOCK = 1

ADDR_PUNCH = 48
LEN_PUNCH = 2